PackageIdentifier: Innovatorved.RealtimeInterviewCopilot
PackageVersion: 0.15.0-beta
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/innovatorved/realtime-interview-copilot/releases/download/v0.15.0-beta/Realtime.Interview.Copilot.Beta-0.15.0-beta-win-x64.exe
    InstallerSha256: c9e29c02d5b758b3f75b1527a2e6ed23fd5698da69d17dfbac1f4d94418bf632
    Scope: user
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    AppsAndFeaturesEntries:
      - DisplayName: Meeting Copilot
        Publisher: Innovatorved
ManifestType: installer
ManifestVersion: 1.6.0
