PackageIdentifier: Innovatorved.RealtimeInterviewCopilot
PackageVersion: 0.15.2-beta
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/innovatorved/realtime-interview-copilot/releases/download/v0.15.2-beta/Realtime.Interview.Copilot.Beta-0.15.2-beta-win-x64.exe
    InstallerSha256: 46fca37381ac12aebb79e6d1bcd482d3a98c5a94cb22e7f87c251c05bf0e8e02
    Scope: user
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    AppsAndFeaturesEntries:
      - DisplayName: Meeting Copilot
        Publisher: Innovatorved
ManifestType: installer
ManifestVersion: 1.6.0
