PackageIdentifier: Innovatorved.RealtimeInterviewCopilot
PackageVersion: 0.15.4-beta
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/innovatorved/realtime-interview-copilot/releases/download/v0.15.4-beta/Realtime.Interview.Copilot.Beta-0.15.4-beta-win-x64.exe
    InstallerSha256: 81dbc7ea220d47ddf6aff67c590bc3079c07e806cf222f232e6e21f453ab71ca
    Scope: user
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    AppsAndFeaturesEntries:
      - DisplayName: Meeting Copilot
        Publisher: Innovatorved
ManifestType: installer
ManifestVersion: 1.6.0
