PackageIdentifier: Innovatorved.RealtimeInterviewCopilot
PackageVersion: 0.15.1-beta
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/innovatorved/realtime-interview-copilot/releases/download/v0.15.1-beta/Realtime.Interview.Copilot.Beta-0.15.1-beta-win-x64.exe
    InstallerSha256: 48514faa18f47a092972b5f3a10fa4b39c994413a417ad79f065399f46e275ab
    Scope: user
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    AppsAndFeaturesEntries:
      - DisplayName: Meeting Copilot
        Publisher: Innovatorved
ManifestType: installer
ManifestVersion: 1.6.0
